config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :omniauth_callbacks => "omniauth_callbacks"}
  resources :users, only: [:show] do
    member do
      get :following, :followers
      resources :favorites, only: [:create, :destroy, :index]
    end
  end
  resources :posts, only: [:new, :create, :show, :destroy] do
    member do
      resources :reactions, only: [:create]
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'start#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
    mount_uploader :image_1, ImageUploader
    mount_uploader :image_2, ImageUploader
    mount_uploader :image_3, ImageUploader
    
    belongs_to :user
    has_many :reactions, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :user_id, presence: true
    validates :image_1, presence: true
    validates :title, length: {maximum: 12}
    validates :comment, length: {maximum: 150}
    
    default_scope -> { order('created_at DESC')}
    
    def self.from_users_followed_by(user)
      followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
      where("user_id IN (#{followed_user_ids})", user_id: user.id).where(created_at: (1.days.ago)..(Time.now))
    end
    
    def favorite?(user)
      favorites.find_by(user_id: user.id)
    end
    
    def favorite!(user)
      favorites.create!(user_id: user.id)
    end
    
    def unfavorite!(user)
      favorites.find_by(user_id: user.id).destroy
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @post = current_user.posts.build
  end
  
  def edit
  end
  
  def create
    @post = current_user.posts.build(post_params)
      if @post.title == ""
        @post.title = "無題"
      end
      if @post.save
        flash["success"] = "投稿しました！"
        redirect_to root_path
      else
        render 'posts/new'
      end
  end
  
  def destroy
    Post.find(params[:id]).destroy
    flash["success"] = "投稿を削除しました"
    redirect_to root_path
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    @reaction = @post.reactions.build
    @reactions = @post.reactions.all
    if @post == nil
      flash["error"] = "該当する投稿はありません。" 
      redirect_to root_path
    end
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :comment, :image_1, :image_2, :image_3)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_followed_user_posts.html.erb
<div class="follow-illust">
    <p>＜フォローユーザーの投稿＞</p>
    <% @followed_user_posts.each do |item| %>
        <div class="post-item">
            <p><%= item.title %></p>
            <div class="post-image">
                <%= link_to image_tag(item.image_1), item %>
            </div>
            <p><%= link_to "#{item.user.name}", item.user %></p>
        </div>
    <% end %>
    <div class="kaminari">
        <%= paginate @followed_user_posts, :param_name => 'follow_page' %>
    </div>
</div>

app/views/posts/_post.html.erb
<div class="show-item">
    <div class="post-show">
        <div class="show-image">
            <%= link_to image_tag(post.image_1), post_path(post.id) %>
        </div>
    </div>
    <ul class="info">
        <li><%= post[:created_at].strftime("%Y年%m月%d日 %H:%M") %></li>
        <li><%= post.title %></li>
        <li>コメント：<%= post.reactions.count %></li>
        <li>お気に入り：<%= post.favorites.count %></li>
         <% if user_signed_in? && post.user_id == current_user.id %>
            <li><%= link_to "削除", post, method: :delete %></li>
         <% end %>
    </ul>
</div>

app/views/posts/new.html.erb
<div class="container">
    <div class="col-md-4 col-md-offset-4">
        <h3 class="secsion-title">新規投稿</h3>
        
        <%= form_for(@post) do |f| %>
        
            <%= render 'shared/error_messages', object: f.object %>
            
            <div class="form-group">
                <%= f.label :image_1 %>  
                <%= f.file_field :image_1 %>
            </div>
            
            <div class="form-group">
                <%= f.text_field :title, autofocus: true, placeholder:"タイトル（12文字以内）", class:"form-control" %>
            </div>
          
            <div class="form-group">
                <%= f.text_field :comment, placeholder:"コメント", class:"form-control" %>
            </div>
          
            <div class="form-group">
                <%= f.label :image_2 %>  
                <%= f.file_field :image_2 %>
            </div>
            
            <div class="form-group">
                <%= f.label :image_3 %>  
                <%= f.file_field :image_3 %>
            </div>
            
            <div class="form-group">
                <%= f.submit "投稿", class:"btn btn-md btn-primary" %>
            </div>
        <% end %>
        
    </div>
</div>

app/views/posts/show.html.erb
<div class="post-user-comment">
    <h5>タイトル</h5>
    <p><%= @post.title %></p>
    <h5>投稿者コメント</h5>
    <p><%= @post.comment %></p>
</div>
<div class="container-fluid">
<div class="row">
    <div class="col-md-10 secsion">
        <div id="carousel" class="carousel slide" data-interval="false">
             <div class="carousel-inner" role="listbox">
                
                <div class="item active post-show-image">
                    <%= image_tag @post.image_1 %>
                </div>
                <% if @post.image_2? %>
                    <div class="item post-show-image">
                        <%= image_tag @post.image_2 %>
                    </div>
                <% end %>
                <% if @post.image_3? %>
                    <div class="item post-show-image">
                        <%= image_tag @post.image_3 %>
                    </div>
                <% end %>
                
            </div>
            
            <% if @post.image_2? || @post.image_3? %>   
                <a class="right" href="#carousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
                <a class="left" href="#carousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
            <% end %>
            
        </div>
        
        <%= render 'users/favorite' %>
        
    </div>
    
    <div class="col-md-2 secsion">
        <%= link_to user_path(@post.user.id) do %>
            <div class="post-user-field">
                <div class="post-user-image">
                    <%= image_tag @post.user.image %>
                </div>
                <div class="post-user-info">
                    <li>投稿者</li>
                    <li><%= @post.user.name %></li>
                </div>
            </div>
        <% end %>
    <%= render 'users/follow' %>
    
    <div class="other-post">
        <% if @post.image_2? %>
            <div class="other-post-image">
                <%= image_tag @post.image_2 %>
            </div>
        <% end %>
        <% if @post.image_3? %>
            <div class="other-post-image">
                <%= image_tag @post.image_3 %>
            </div>
        <% end %>
    </div>
    
    <div>
        <%= form_for(@reaction) do |f| %>
            <div class="form-group">
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.text_field :comment, placeholder:"コメント", class:"form-control"  %>
            </div>
            <div class="form-group">
                <%= f.submit "コメントする" %>
            </div>
        <% end %>
    </div>
    
    <div class="post-comment">
        <% @reactions.each do |reaction| %>
        <div class="comment-item">
            <p><%= reaction.user.name %></p>
            <p><%= reaction.comment %></p>
        </div>
        <% end %>
    </div>
</div>
</div>